language: node_js
branches:
    only:
        - master
        - /^greenkeeper/.*$/
cache:
    yarn: true
    directories:
        - node_modules
notifications:
    email: false
node_js:
    - '6'
services:
    - postgresql
before_script:
    - ./node_modules/.bin/lerna bootstrap
    - psql -c 'create database travis_ci_test;' -U postgres
script:
    - DATABASE_URL=postgres://postgres:@localhost:5432/travis_ci_test ./node_modules/.bin/lerna run test:prod && lerner run build
after_success:
    - ./node_modules/.bin/lerna run report-coverage
