language: node_js
branches:
    only:
        - master
        - /^greenkeeper/.*$/
cache:
    yarn: true
    directories:
        - node_modules
notifications:
    email: false
node_js:
    - '6'
before_script:
    - ./node_modules/.bin/lerner bootstrap
script:
    - ./node_modules/.bin/lerner run test:prod && lerner run build
after_success:
    - ./node_modules/.bin/lerner run report-coverage
