language: node_js
branches:
    only:
        - master
        - /^greenkeeper/.*$/
cache:
    yarn: true
    directories:
        - node_modules
notifications:
    email: false
node_js:
    - '6'
addons:
    postgresql: "9.6"
services:
    - postgresql
before_script:
    - psql -c 'select version();' -U postgres
    - psql -c 'create database travis_ci_test;' -U postgres
script:
    - npm run bootstrap
    - npm run build-all
    - npm run build-tests-all
    - DATABASE_URL=postgres://postgres:@localhost:5432/travis_ci_test npm run test-all
    - npm run lint-all
    - npm run style-all
after_success:
    - npm run report-coverage
deploy:
    skip_cleanup: true
    provider: script
    script: npm run deploy-docs
    on:
        branch: master
